import React from "react";
import Form from "./Form";

function Body() {
  return (
    <div className="mt-5 px-2">
      <h1 className="text-3xl text-[#005734] font-bold text-center">
        Samanta Content Evaluator
      </h1>
      <div className="flex flex-col-reverse lg:flex-row mt-5">
        <p className="lg:max-w-[80%] mt-4 lg:leading-7 leading-5 text-sm lg:text-[17px] w-full font-[450] text-justify">
          Samanta Content Evaluator will assess the content, is it generated by
          AI or Humans, measures the confidence level of the content, detect
          plagiarism, and analyze various aspects like character count, sentence
          count, and paragraph count…. Try it now
        </p>

        <img
          src="/images/samanta.png"
          alt=""
          className="m-auto mt-4 w-[200px] lg:w-[20%] h-[150px] object-contain lg:object-cover"
        />
      </div>

      <Form />
    </div>
  );
}

export default Body;
